En esta primera parte del proyecto, los estudiantes realizarán un análisis preliminar del dataset utilizando NumPy. El objetivo es familiarizarse con los datos y realizar operaciones básicas de manipulación y análisis.

Instrucciones

1-. Configuración Inicial del Proyecto:
* Crea un repositorio en GitHub para tu proyecto.
* Configura dos ramas en tu repositorio: main y development.
* Agrega un archivo README.md con una descripción del proyecto, instrucciones de instalación y uso.

2-. Carga y Preprocesamiento de Datos:
* Carga los datos del archivo CSV utilizando NumPy.
* Realiza un preprocesamiento básico para asegurarte de que los datos estén limpios y listos para su análisis.

3-. Exploración de Datos:
* Calcula el total de ventas por categoría de producto.
* Calcula el promedio de ventas diarias por categoría de producto.
* Identifica las categorías de productos con mayores y menores ventas.

4-. Manipulación de Datos:
* Filtra los datos para mostrar solo las ventas de una categoría de producto específica.
* Realiza operaciones de suma, resta, multiplicación y división en los datos para obtener estadísticas adicionales.

In [ ]:
import numpy as np

def cargar_datos(ruta_archivo):
    # Carga los datos del archivo CSV utilizando NumPy
    datos = np.genfromtxt(ruta_archivo, delimiter=',', skip_header=1)
    return datos

if __name__ == "__main__":
    ruta_archivo = '/content/retail_sales_dataset.csv'
    datos = cargar_datos(ruta_archivo)
    print(datos)

[[   1.   nan   nan ...    3.   50.  150.]
 [   2.   nan   nan ...    2.  500. 1000.]
 [   3.   nan   nan ...    1.   30.   30.]
 ...
 [ 998.   nan   nan ...    4.   25.  100.]
 [ 999.   nan   nan ...    3.   50.  150.]
 [1000.   nan   nan ...    4.   30.  120.]]

In [ ]:
# Al pedir limpieza de datos se refiere a buscar valores vacíos o erróneos
# Se tendrá:
# Columna 0: Transaction ID
# Columna 1: Date
# Columna 2: Customer ID
# Columna 3: Gender
# Columna 4: Age
# Columna 5: Product Category (Beauty, Clothing, Electronics)
# Columna 6: Quantity
# Columna 7: Price per Unit
# Columna 8: Total Amount

CARGA Y PREPROCESAMIENTO DE DATOS

In [ ]:
# Se procede a utilizar pandas, tema ya visto en clases y por tanto se puede ocupar dicha información

import pandas as pd

In [ ]:
df = pd.read_csv('/content/retail_sales_dataset.csv')
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [ ]:
# Métodos esenciales antes de analizar un DataSet:
# 1
print(f'{df.shape[0]} filas, {df.shape[1]} columnas')
print()
# 2 Primeras 5 filas
print(df.head())
print()
# 3 Tipos de datos y valores no nulos por columna
df.info()
# No hay presencia de nulos y por tanto todas las celdas contienen datos. CHECK
print()
# 4 Estadísticas descriptivas de columnas numéricas
print(df.describe())
print()
# 5 Últimas 5 filas
print(df.tail())

1000 filas, 9 columnas

   Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  2023-11-24     CUST001    Male   34           Beauty
1               2  2023-02-27     CUST002  Female   26         Clothing
2               3  2023-01-13     CUST003    Male   50      Electronics
3               4  2023-05-21     CUST004    Male   37         Clothing
4               5  2023-05-06     CUST005    Male   30           Beauty

   Quantity  Price per Unit  Total Amount
0         3              50           150
1         2             500          1000
2         1              30            30
3         1             500           500
4         2              50           100

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

     Transaction ID        Date Customer ID  Gender  Age Product Category  \
995             996  2023-05-16     CUST996    Male   62         Clothing
996             997  2023-11-17     CUST997    Male   52           Beauty
997             998  2023-10-29     CUST998  Female   23           Beauty
998             999  2023-12-05     CUST999  Female   36      Electronics
999            1000  2023-04-12    CUST1000    Male   47      Electronics

     Quantity  Price per Unit  Total Amount
995         1              50            50
996         3              30            90
997         4              25           100
998         3              50           150
999         4              30           120

In [ ]:
# Se usa df.unique() para determinar qué tipo de información contiene la categoría de producto
df['Product Category'].unique()

array(['Beauty', 'Clothing', 'Electronics'], dtype=object)

EXPLORACIÓN DE DATOS

In [ ]:
# VENTAS TOTALES POR CATEGORÍA

electronics = df[df['Product Category'] == 'Electronics']
venta_electronics = electronics['Total Amount'].sum()
print(f'Ventas totales Electronics: {venta_electronics}')

beauty = df[df['Product Category'] == 'Beauty']
venta_beauty = beauty['Total Amount'].sum()
print(f'Ventas totales Beauty: {venta_beauty}')

clothing = df[df['Product Category'] == 'Clothing']
venta_clothing = clothing['Total Amount'].sum()
print(f'Ventas totales Clothing: {venta_clothing}')

Ventas totales Electronics: 156905
Ventas totales Beauty: 143515
Ventas totales Clothing: 155580

In [ ]:
## ALTERNATIVA USANDO GROUPBY
df.groupby('Product Category')['Total Amount'].sum()

Product Category
Beauty         143515
Clothing       155580
Electronics    156905
Name: Total Amount, dtype: int64

In [ ]:
# PROMEDIO DE VENTAS DIARIAS POR CATEGORÍA USANDO GROUPBY

df.groupby('Product Category')['Total Amount'].mean()

Product Category
Beauty         467.475570
Clothing       443.247863
Electronics    458.786550
Name: Total Amount, dtype: float64

In [ ]:
# PRODUCTOS CON MAYOR Y MENOR VENTAS

mayor_ventas = (df.groupby('Product Category')['Total Amount'].sum()).idxmax()    # Método .idxmax() devuelve el nombre de la columna (o sea el índice) donde se encuentra
                                                                                  # el valor máximo
print(f'El producto con mayor ventas corresponde a la categoría de: {mayor_ventas}')

menor_ventas = (df.groupby('Product Category')['Total Amount'].sum()).idxmin()
print(f'El producto con menor ventas corresponde a la categoría de: {menor_ventas}')

El producto con mayor ventas corresponde a la categoría de: Electronics
El producto con menor ventas corresponde a la categoría de: Beauty

MANIPULACIÓN DE DATOS

In [ ]:
# Mostrar solo las ventas de una categoría de producto específica
# Se elige trabajar con la categoria 'Electronics' por ser solamente la de mayor peso en la tienda al ser la que más vende

electronics = df[df['Product Category'] == 'Electronics'].copy()    # Se crea una copia para no modificar el df original


# OPERACIONES A REALIZAR:
# Se cobrará un iva, se hará descuentos especiales aplicados al precio final y se crearán nuevas columnas para operar.

# Se crea un cargo por iva del 19%
electronics['IVA (19%)'] = electronics['Total Amount'] * 0.19

# Se actualiza el precio con iva incluido
electronics['Total (IVA inlcuido)'] = electronics ['Total Amount'] + electronics['IVA (19%)']

# Suponiendo descuento de la tienda de un 20% (se aplica sobre el producto, no el valor final)
electronics['Descuento promo'] = electronics['Total (IVA inlcuido)'] - electronics['Total Amount'] * 0.02

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,IVA (19%),Total (IVA inlcuido),Descuento promo
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,5.70,35.70,35.10
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100,19.00,119.00,117.00
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600,114.00,714.00,702.00
12,13,2023-08-05,CUST013,Male,22,Electronics,3,500,1500,285.00,1785.00,1755.00
14,15,2023-01-16,CUST015,Female,42,Electronics,4,500,2000,380.00,2380.00,2340.00
...,...,...,...,...,...,...,...,...,...,...,...,...
988,989,2023-12-28,CUST989,Female,44,Electronics,1,25,25,4.75,29.75,29.25
991,992,2023-08-21,CUST992,Female,57,Electronics,2,30,60,11.40,71.40,70.20
992,993,2023-02-06,CUST993,Female,48,Electronics,3,50,150,28.50,178.50,175.50
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,28.50,178.50,175.50
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,22.80,142.80,140.40